var programs = [
                    "Bachelor of Elementary Education",
                    "Bachelor of Secondary Education",
                    "Bachelor of Technical Teacher Education",
                    "BS in Industrial Education",
                    "BS in Architecture",
                    "BS in Civil Engineering",
                    "BS in Marine Engineering",
                    "BS in Electronics and Communications Engineering",
                    "BS in Electrical Engineering",
                    "BS in Mechanical Engineering",
                    "BS in Computer Engineering",
                    "BS in Industrial Engineering",
                    "BS in Chemical Engineering",
                    "BS in Agricultural Engineering",
                    "BS in Aeronautical Engineering",
                    "BS in Geodetic Engineering",
                    "BS in Mining Engineering",
                    "BS in Office Administration",
                    "BS in Customs Administration",
                    "BS in Public Administration",
                    "AB in Public Administration",
                    "BS in Legal Management",
                    "BS in Agriculture",
                    "Bachelor of Agricultural Technology",
                    "BS in Forestry",
                    "BS in Fisheries and Aquatic Recources",
                    "BS Aeronautical Engineering",
                    "BS in Management Accounting",
                    "Bachelor of Fine Arts",
                    "BS in Interior Design",
                    "BS in Business Administration",
                    "BS in Accountancy",
                    "BSBA in Marketing Management",
                    "BSBA in Financial Management",
                    "BSBA in Human Resource Development Management",
                    "BSBA in Management",
                    "BS in Accounting Technology",
                    "BS in Entrepreneurship",
                    "BSBA in Management Accounting",
                    "BSBA in Operations Management",
                    "BS in Entrepreneurial Management",
                    "AB in Economics",
                    "BSBA in Business Economics",
                    "BSBA in Entrepreneurship",
                    "BS in Economics",
                    "BSBA in Banking and Finance",
                    "AB in Communication",
                    "AB in Mass Communication",
                    "AB in Multimedia Arts",
                    "AB in Journalism",
                    "BS in Developmental Communication",
                    "Bachelor of Library and Information Science",
                    "AB in Philosophy",
                    "AB in History",
                    "AB in Literature",
                    "BS in Information Technology",
                    "BS in Computer Science",
                    "BS in Information System",
                    "BS in Information and Communications Technology",
                    "BS in Software Engineering",
                    "AB in English",
                    "AB in Filipino",
                    "BS in Marine Transportation",
                    "BS in Nursing",
                    "BS in Medical Technology",
                    "BS in Pharmacy",
                    "BS in Physical Theraphy",
                    "BS in Nutrition and Dietetics",
                    "BS in Respiratory Theraphy",
                    "BS in Occupational Therapy",
                    "BS in Midwifery",
                    "Bachelor of Music in Music Education",
                    "BS in Industrial Technology",
                    "Bachelor of Technology Teacher Education",
                    "BS in Aircraft Maintenance Technology",
                    "BS in Food Technology",
                    "BS in Computer Technology",
                    "AB in Theology",
                    "BS in Biology",
                    "BS in Mathematics",
                    "BS in Chemistry",
                    "BS in Environmental Science",
                    "BS in Geology",
                    "BS in Applied Mathematics",
                    "BS in Applied Physics",
                    "BS in Physics",
                    "BS in Marine Biology",
                    "BS in Statistic",
                    "BS in Zoology",
                    "BS in Criminology",
                    "BS in Psychology",
                    "AB in Political Science",
                    "BS in Social Work",
                    "AB in Psychology",
                    "AB in Sociology",
                    "BS in Community Development",
                    "AB in Social Science",
                    "BS in Hotel and Restaurant Management",
                    "BS in Tourism Management",
                    "BS in Hospitality Management",
                    "BS in Tourism",
                    "BS in International Hospitality Management",
                    "BS in Travel Management"
                ]
